apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: mern-app
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30080
