apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: mern-app
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30081
